-- create table employee -
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    STAFF_CODE      CHAR(8)         NOT NULL,
    STAFF_NAME      VARCHAR(100)   NOT NULL,
    STAFF_ACCOUNT      VARCHAR(255)   NOT NULL,
    STAFF_PASS      VARCHAR(255)    NOT NULL,
    CONSTRAINT TOUR_PK1 PRIMARY KEY(STAFF_CODE)
)
;

-- create table employee -
CREATE TABLE IF NOT EXISTS CONTENT (
    STAFF_CODE      CHAR(8)         NOT NULL,
    STAFF_NAME      VARCHAR(100)   NOT NULL,
    STAFF_ACCOUNT      VARCHAR(255)   NOT NULL,
    STAFF_PASS      VARCHAR(255)    NOT NULL,
    CONSTRAINT TOUR_PK1 PRIMARY KEY(STAFF_CODE)
)
;