INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_ACCOUNT, STAFF_PASS) VALUES ('00000001', 'HUNGNV', 'account1', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_ACCOUNT, STAFF_PASS) VALUES ('00000002', 'HUNGNV', 'account2', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_ACCOUNT, STAFF_PASS) VALUES ('00000003', 'HUNGNV', 'account3', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_ACCOUNT, STAFF_PASS) VALUES ('00000004', 'HUNGNV', 'account4', 'password');
INSERT INTO EMPLOYEE (STAFF_CODE, STAFF_NAME, STAFF_ACCOUNT, STAFF_PASS) VALUES ('00000005', 'HUNGNV', 'account5', 'password');

COMMIT;